"""Non-SI units in terms of SI."""

J = 1
W = 1
KILO = 1000
MINUTE = 60
HOUR = 3600
WH = W * HOUR
kW = KILO * W
kWH = KILO * WH
H2_LHV = 33330 * WH  # J/kg
HOURS_PER_YEAR = 365 * 24  # hours
EUR = 1  # euros = pounds = dollars (approx.)
PERCENT = 0.01


HYUNDAI_NEXO_FUEL_CONSUMPTION = 0.84  # 0.84 kg / 100 km
AV_DAILY_MILEAGE = 40  # km
DAILY_HYUNDAI_NEXO_ENERGY_CONSUMPTION = (
    HYUNDAI_NEXO_FUEL_CONSUMPTION * H2_LHV / 100 * AV_DAILY_MILEAGE
)  # 40315968 J
YEARLY_HYUNDAI_NEXO_ENERGY_CONSUMPTION = DAILY_HYUNDAI_NEXO_ENERGY_CONSUMPTION * 365
